### ISSUE TITLE
xsv cat could take a csv of paths as input?

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/xsv#121]
- [x] -i
- [x] -I

**Comment by diegantobass** [comment]
What happened to no coding after 22? You get Prophetic's lucid dreams inducing device as soon as it comes out ([this is not a joke](https://fortune.com/2023/11/30/lucid-dream-startup-prophetic-headset-prepare-meetings-while-sleeping/))

**Comment by Yomguithereal** [comment]
Oh no I have to start a startup now…

**Comment by diegantobass** [comment]
"We are not hackers"
