### ISSUE TITLE
Trouble updating to `xsv v0.13.0-medialab21`

### ISSUE THREAD

**Issue by MiguelLaura** [medialab/xsv#66]
error: implementation of `Debug` is not general enough
  --> src/xan/interpreter.rs:64:5
   |
61 | #[derive(Debug, Clone)]
   |          ----- in this derive macro expansion
...
64 |     function: Function,
   |     ^^^^^^^^^^^^^^^^^^ implementation of `Debug` is not general enough
   |
   = note: `Debug` would have to be implemented for the type `for<'a> fn(BoundArguments<'a>) -> Result<DynamicValue, CallError>`
   = note: ...but `Debug` is actually implemented for the type `fn(BoundArguments<'0>) -> Result<DynamicValue, CallError>`, for some specific lifetime `'0`
   = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `xsv` (bin "xsv") generated 1 warning
error: could not compile `xsv` due to previous error; 1 warning emitted
error: failed to compile `xsv v0.13.0-medialab21 (https://github.com/medialab/xsv.git?rev=72df6098215784d38f000fae654c3bf02bfc3267#72df6098)`, intermediate artifacts can be found at `/tmp/cargo-installrbwjci`

**Comment by MiguelLaura** [comment]
J'ai réussi à récupérer la version 0.13.0-medialab20 par contre.

**Comment by Yomguithereal** [comment]
Can you rustup update and tell me if this fixes it?

**Comment by MiguelLaura** [comment]
Fixed! Thank you!

**Comment by Yomguithereal** [comment]
The sad part is that I don’t know how to use an older rust compiler to reproduce and maybe fix so that it does not happen again :’(
