### ISSUE TITLE
Feedbacks on the love letter

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/xsv#92]
- [x] mention the fact that CSV is a collective idea
- [x] add a clickbaity abstract
- [x] Mention the non palindromic escape
- [x] human readability and editability addendum

**Comment by Yomguithereal** [comment]
@robindemourat I added a blurb on CSV being an free and open collective idea.

**Comment by boogheta** [comment]
I did a few minor modification directly within this commit: https://github.com/medialab/xsv/commit/421b19204e9d94c836169f061806f3d197782cde
